spring.application.name=SpringMVC_13_MiniProjectEmployeeAdv
#Datasource properties
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=yogesh
spring.datasource.password=yogesh1234

#jpa
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

#server
server.port=9797

#viewResolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
