spring.application.name=SpringRest_MINI_Proj

#datasource
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=yogesh
spring.datasource.password=yogesh1234


#spring rest cnfgs
server.port=7878
server.servlet.context-path=/SpringRest_MINI_Proj

#jpa cnfgs
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update